defaults:
  - exp: ???
  - dataset: ???
  - model: noop # Not necessarily needed if exp=histos
  - launcher: local
  - _self_

# Default parameters, are overridden by model specific parameters
train:
  lr: 0.001
  epochs: 10
  dropout: 0.1
  lr_warmup: 0
  batch_size: 50
  clip_grad_norm: 5
  validation_split: 0.2
  clamp_samples: null

devices:
  device: gpu
  pin_memory: true
  non_blocking: true
  dtype: float32 # also can be float16
  eval: gpu # specially for histo filling 

modes:
  train: true
  eval: true
  plot: true
  recycle: false
  wandb: false

data:
  run: 1
  ckpts: checkpoints.pt
  run_dir_base: run_dirs
  run_dir: ${.run_dir_base}/${dataset.key}/${exp.key}/${model.key}/${.run}
