defaults:
  - _base
  - _self_

key: lorentznet

net:
  _target_: models.lorentznet.LorentzNet
  n_scalar: ... # Dynamically derived
  dim_out: ... # Dynamically derived
  n_hidden: 128
  n_layers: 13
  c_weight: 5e-3
  dropout: ${train.dropout}
