defaults:
  - _base
  - _self_

key: transformer
input_level: particles # particles|features

LLoCa:
  active: false # whether to make the data lorentz equivariant
  LLoCa_frames: 5
  LLoCa_frames_inv: 5
  LLoCa_num_scalars: 4
  LLoCa_num_vectors: 4

net:
  _target_: models.transformer.Transformer
  dim_in: ... # Dynamically derived
  dim_out: ... # Dynamically derived
  emb_factor: 64
  num_blocks: 8
  dropout_p: ${train.dropout}
  attention:
    num_heads: 8
    increase_hidden_channels: 8
  mlp:
    k_factor: 2
    activation: relu

train:
  lr: 2e-4 # 2e-4 is reccomended by LLoCa paper, 0.001 is what arcturo used
  epochs: 100 # arcturo used 10
  dropout: 0.1
  lr_warmup: 30
  batch_size: 512 # arcturo used 50
  clip_grad_norm: 1
  validation_split: 0.2
  clamp_samples: null
